### ISSUE TITLE
pressing a modifier key shifts focus to the first search result

### ISSUE THREAD

**Issue by zeke** [stefanbuck/jumpcat#16] opened 2021-10-02 23:26 UTC
### Expected Behavior

If I've arrowed down to the nth result, pressing modifier keys should not change the active selection

### What actually happened?

Pressing ctrl, or option, or command, or shift, moves the focus to the first search result

### Anything else we should know?

Hi @stefanbuck 👋🏼 

To reproduce:

1. search for something that returns multiple results
2. press the down arrow a few times
3. press a modifier key

### Version of Jumpcat

0.15.1

**Comment by stefanbuck** [comment] 2021-10-03 20:24
Thanks for raising this issue. Will be fixed in the next release. Do you mind sharing if pressing those keys was intended to perform/check whether a certain action is implemented? If so, what was your intent?

**Comment by zeke** [comment] 2021-10-04 20:12
My intent was to take a screenshot on macOS with cmd-shift-4

**Comment by stefanbuck** [comment] 2021-10-04 20:25
I just fixed it. A new release is coming soon (either today or tomorrow).

**Closed by stefanbuck** 2021-10-04 20:25 UTC
Labels: bug
